---
- name: make emacs source directory
  file:
      path: "{{ ansible_env.HOME }}/emacs-src"
      state: directory

- name: download emacs source
  get_url:
      url: "{{ emacs_source_url }}"
      dest: "{{ ansible_env.HOME }}/emacs-src/emacs.tar.gz"
      mode: 0755

- name: unzip emacs source
  unarchive:
      src: "{{ ansible_env.HOME }}/emacs-src/emacs.tar.gz"
      dest: "{{ ansible_env.HOME }}/emacs-src"

- name: install dependencies
  apt:
      name: "build-essential"
      update_cache: yes
  sudo: yes

- name: install emacs dependencies
  apt:
      name: emacs24
      update_cache: yes
      state: build-dep
  sudo: yes

- name: configure emacs
  command: ./configure
  args:
      chdir: "{{ ansible_env.HOME }}/emacs-src/emacs-24.5/"

- name: make emacs
  command: make
  args:
      chdir: "{{ ansible_env.HOME }}/emacs-src/emacs-24.5/"

- name: make install emacs
  command: make install
  args:
      chdir: "{{ ansible_env.HOME }}/emacs-src/emacs-24.5/"
  sudo: yes

- name: download .emacs.d
  git:
      repo: https://github.com/el-ethan/.emacs.d.git
      dest: "{{ ansible_env.HOME }}/.emacs.d"
