---
- name: add enpass to sources
  lineinfile:
      dest: /etc/apt/sources.list.d/enpass.list
      line: "deb http://repo.sinew.in/ stable main"
      create: yes
  become: true

- name: add key for enpass
  apt_key:
      url: http://repo.sinew.in/keys/enpass-linux.key
  become: true

- name: install enpass
  apt: name=enpass state=present update_cache=yes
  become: true
