---
- name: install apt packages
  apt: name={{ item }} state=present
  become: true
  with_items:
      - git
      - gpick
      - terminator
      - tree
      - virtualbox-qt
      - clipit
      - ipython
      - editorconfig
      - xclip
      - silversearcher-ag
      - nautilus-dropbox
      - indicator-multiload
      - python-pip
      - python-psutil
      - python-rope
      - python-flake8
      - python-autopep8
      - python3-dev
      - virtualenv
      - virtualenvwrapper
      - texlive-latex-extra
      - gnome-dictionary
      - mysql-server
      - libmysqlclient-dev
      - flake8

- name: install PyPi packages
  pip: name={{ item }} state=present
  with_items:
      - importmagic
      - pdbpp
